import { useLocation, useNavigate } from "react-router-dom";
import {
  FaArrowLeft,
  FaShieldAlt,
  FaFileAlt,
  FaLock,
  FaDatabase,
  FaUsers,
  FaExclamationTriangle,
  FaLightbulb,
  FaDownload,
  FaCopy,
  FaPrint,
} from "react-icons/fa";

import { jsPDF } from "jspdf";

function Analysis() {
  const location = useLocation();
  const navigate = useNavigate();

  const data = location.state?.analysis;

  const handleDownloadPDF = () => {
  const doc = new jsPDF();

  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;

  const margin = 20;
  const lineHeight = 7;

  let y = 20;

  const checkPage = (spaceNeeded = lineHeight) => {
    if (y + spaceNeeded > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const addTitle = (text) => {
    checkPage(15);

    doc.setFontSize(16);
    doc.setFont(undefined, "bold");
    doc.text(text, margin, y);

    y += 10;

    doc.setFont(undefined, "normal");
  };

  const addParagraph = (text) => {
    if (!text) return;

    doc.setFontSize(12);

    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);

    lines.forEach((line) => {
      checkPage();

      doc.text(line, margin, y);

      y += lineHeight;
    });

    y += 5;
  };

  const addList = (title, items) => {
    if (!items || items.length === 0) return;

    addTitle(title);

    doc.setFontSize(12);

    items.forEach((item) => {
      const lines = doc.splitTextToSize(
        `• ${item}`,
        pageWidth - margin * 2
      );

      lines.forEach((line) => {
        checkPage();

        doc.text(line, margin, y);

        y += lineHeight;
      });
    });

    y += 6;
  };

  // ===========================
  // Header
  // ===========================

  doc.setFontSize(22);
  doc.setFont(undefined, "bold");
  doc.text("AgreeWise AI Analysis Report", margin, y);

  y += 15;

  doc.setFontSize(14);
  doc.setFont(undefined, "normal");

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    margin,
    y
  );

  y += 10;

  doc.text(
    `Safety Score: ${data.safety_score}/10`,
    margin,
    y
  );

  y += 15;

  // ===========================
  // Sections
  // ===========================

  addTitle("Summary");
  addParagraph(data.summary);

  addList("Privacy", data.privacy);

  addList("Collected Data", data.collected_data);

  addList("Shared Data", data.shared_data);

  addList("Hidden Clauses", data.hidden_clauses);

  addList("Risks", data.risks);

  addTitle("Recommendation");
  addParagraph(data.recommendation);

  // ===========================
  // Footer
  // ===========================

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.text(
      `Page ${i} of ${pages}`,
      pageWidth - 35,
      pageHeight - 10
    );

    doc.text(
      "Generated by AgreeWise AI",
      margin,
      pageHeight - 10
    );
  }

  const date = new Date()
    .toISOString()
    .split("T")[0];

  doc.save(`AgreeWise_Report_${date}.pdf`);
};

const handleCopy = async () => {
  const report = `
AgreeWise AI Report

Safety Score:
${data.safety_score}/10

Summary:
${data.summary}

Privacy:
${data.privacy?.join("\n")}

Collected Data:
${data.collected_data?.join("\n")}

Shared Data:
${data.shared_data?.join("\n")}

Hidden Clauses:
${data.hidden_clauses?.join("\n")}

Risks:
${data.risks?.join("\n")}

Recommendation:
${data.recommendation}
`;

  await navigator.clipboard.writeText(report);

  alert("Report copied successfully!");
};

const handlePrint = () => {
  window.print();
};

  if (!data) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center text-white">
        No analysis found.
      </div>
    );
  }

  
  const Card = ({ icon, title, children }) => (
    <div className="rounded-3xl bg-white/5 backdrop-blur-xl border border-white/10 p-6 shadow-lg">
      <div className="flex items-center gap-3 mb-5">
        <div className="text-blue-400 text-2xl">{icon}</div>
        <h2 className="text-2xl font-bold">{title}</h2>
      </div>

      {children}
    </div>
  );

  return (
    <div className="min-h-screen bg-[#030712] text-white px-6 py-12">

      <div className="max-w-7xl mx-auto">

        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-slate-300 hover:text-blue-400 mb-8"
        >
          <FaArrowLeft />
          Back
        </button>

        <h1 className="text-5xl font-black mb-3">
          AI Agreement Analysis
        </h1>

        <p className="text-slate-400 mb-10">
          Generated using Gemini AI
        </p>

        <div className="flex flex-wrap gap-4 mb-10">

  <button
    onClick={handleDownloadPDF}
    className="flex items-center gap-2 px-5 py-3 rounded-xl bg-blue-600 hover:bg-blue-700 transition"
  >
    <FaDownload />
    Download PDF
  </button>

  <button
    onClick={handleCopy}
    className="flex items-center gap-2 px-5 py-3 rounded-xl bg-green-600 hover:bg-green-700 transition"
  >
    <FaCopy />
    Copy Report
  </button>

  <button
    onClick={handlePrint}
    className="flex items-center gap-2 px-5 py-3 rounded-xl bg-violet-600 hover:bg-violet-700 transition"
  >
    <FaPrint />
    Print
  </button>

</div>

        {/* Safety Score */}
        <div className="rounded-3xl bg-gradient-to-r from-blue-600 to-violet-600 p-8 mb-10">

          <p className="text-lg">Safety Score</p>

          <h2 className="text-7xl font-black mt-2">
            {data.safety_score}/10
          </h2>

        </div>

        <div className="grid lg:grid-cols-2 gap-8">

          <Card
            icon={<FaFileAlt />}
            title="Summary"
          >
            <p className="text-slate-300 leading-8">
              {data.summary}
            </p>
          </Card>

          <Card
            icon={<FaLock />}
            title="Privacy"
          >
            <ul className="space-y-3">
              {data.privacy?.map((item, index) => (
                <li key={index}>• {item}</li>
              ))}
            </ul>
          </Card>

          <Card
            icon={<FaDatabase />}
            title="Collected Data"
          >
            <ul className="space-y-3">
              {data.collected_data?.map((item, index) => (
                <li key={index}>• {item}</li>
              ))}
            </ul>
          </Card>

          <Card
            icon={<FaUsers />}
            title="Shared Data"
          >
            <ul className="space-y-3">
              {data.shared_data?.map((item, index) => (
                <li key={index}>• {item}</li>
              ))}
            </ul>
          </Card>

          <Card
            icon={<FaExclamationTriangle />}
            title="Hidden Clauses"
          >
            <ul className="space-y-3">
              {data.hidden_clauses?.map((item, index) => (
                <li key={index}>• {item}</li>
              ))}
            </ul>
          </Card>

          <Card
            icon={<FaShieldAlt />}
            title="Risks"
          >
            <ul className="space-y-3">
              {data.risks?.map((item, index) => (
                <li key={index}>• {item}</li>
              ))}
            </ul>
          </Card>

        </div>

        <div className="mt-10">

          <Card
            icon={<FaLightbulb />}
            title="AI Recommendation"
          >
            <p className="leading-8 text-slate-300">
              {data.recommendation}
            </p>
          </Card>

        </div>

      </div>

    </div>
  );
}

export default Analysis;